branch: nixpkgs-unstable

eval:
  record_store_paths: true
  systems:
    - x86_64-linux
    - aarch64-darwin

pkgs:
  ruby:
    nixpkgs_attributes:
      - ruby
      - ruby_3_4
      - ruby_3_3
      - ruby_3_2
      - ruby_3_1
    tests:
      - ruby --version | grep $VERSION

  python:
    nixpkgs_attributes:
      - python3
      - python314
      - python313
      - python312
      - python311
      - python310
    tests:
      - python --version | grep $VERSION

  node:
    nixpkgs_attributes:
      - nodejs
      - nodejs_24
      - nodejs_22
      - nodejs_20
      - nodejs_18
    tests:
      - node --version | grep $VERSION
